## Importing Libraries

In [187]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

## Data Loading

In [188]:
data=pd.read_csv(r"C:\Users\farza\OneDrive\Documents\inventory risk dataset.csv")
data

,currentStock,averageDailyDemand,leadTimeDays,demandVariance,supplierRiskScore,safetyStock,reorderPoint,incomingStockDays,pendingOrderQty,isCriticalItem,riskScore,riskTier
0,261.35,111.63,31.33,87.34,79.46,353.47,2101.83,0.0,0.00,0,46.16,medium
1,2325.77,118.31,12.54,79.48,42.76,1181.83,1923.89,0.0,0.00,0,14.87,low
2,5539.17,118.64,10.27,9.96,24.81,872.49,1481.80,6.2,1006.01,0,1.91,low
3,883.04,62.47,33.89,38.02,29.38,441.84,1500.52,0.0,0.00,1,32.76,medium
4,485.50,35.18,31.37,42.75,47.36,228.26,780.16,6.1,318.22,0,25.13,low
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,37.27,8.16,36.36,119.21,69.71,55.96,204.35,26.1,93.14,0,47.50,medium
9996,814.32,161.61,41.19,67.33,63.90,1576.87,4905.34,0.0,0.00,1,56.71,medium
9997,29.08,11.39,47.21,88.94,77.15,57.60,326.59,3.1,122.56,0,53.98,medium
9998,3324.85,50.84,14.74,10.30,4.21,494.49,869.20,0.0,0.00,0,4.90,low
9999,767.69,182.69,44.89,99.44,61.41,962.20,5063.10,13.8,2474.82,1,47.64,medium

# Exploratory Data Analysis

In [171]:
data.isna().sum()

currentStock          0
averageDailyDemand    0
leadTimeDays          0
demandVariance        0
supplierRiskScore     0
safetyStock           0
reorderPoint          0
incomingStockDays     0
pendingOrderQty       0
isCriticalItem        0
riskScore             0
riskTier              0
dtype: int64

In [172]:
data.head()

,currentStock,averageDailyDemand,leadTimeDays,demandVariance,supplierRiskScore,safetyStock,reorderPoint,incomingStockDays,pendingOrderQty,isCriticalItem,riskScore,riskTier
0,261.35,111.63,31.33,87.34,79.46,353.47,2101.83,0.0,0.00,0,46.16,medium
1,2325.77,118.31,12.54,79.48,42.76,1181.83,1923.89,0.0,0.00,0,14.87,low
2,5539.17,118.64,10.27,9.96,24.81,872.49,1481.80,6.2,1006.01,0,1.91,low
3,883.04,62.47,33.89,38.02,29.38,441.84,1500.52,0.0,0.00,1,32.76,medium
4,485.50,35.18,31.37,42.75,47.36,228.26,780.16,6.1,318.22,0,25.13,low

In [173]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   currentStock        10000 non-null  float64
 1   averageDailyDemand  10000 non-null  float64
 2   leadTimeDays        10000 non-null  float64
 3   demandVariance      10000 non-null  float64
 4   supplierRiskScore   10000 non-null  float64
 5   safetyStock         10000 non-null  float64
 6   reorderPoint        10000 non-null  float64
 7   incomingStockDays   10000 non-null  float64
 8   pendingOrderQty     10000 non-null  float64
 9   isCriticalItem      10000 non-null  int64
 10  riskScore           10000 non-null  float64
 11  riskTier            10000 non-null  object
dtypes: float64(10), int64(1), object(1)
memory usage: 937.6+ KB

In [174]:
data.describe()

,currentStock,averageDailyDemand,leadTimeDays,demandVariance,supplierRiskScore,safetyStock,reorderPoint,incomingStockDays,pendingOrderQty,isCriticalItem,riskScore
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1344.457789,102.870902,30.523945,71.545239,50.510000,669.254399,2239.596175,4.294330,356.136412,0.410700,37.268464
std,1776.989236,56.551186,15.599717,45.394788,29.441172,435.519794,1551.681341,9.006769,732.226520,0.491985,27.865025
min,0.040000,5.000000,5.030000,0.030000,0.010000,16.050000,39.210000,0.000000,0.000000,0.000000,0.000000
25%,164.930000,54.077500,16.130000,26.907500,23.020000,316.332500,997.485000,0.000000,0.000000,0.000000,11.330000
50%,657.890000,102.920000,29.945000,70.465000,52.265000,602.795000,1925.740000,0.000000,0.000000,0.000000,32.740000
75%,1770.817500,152.135000,44.292500,114.180000,77.265000,955.992500,3207.202500,3.225000,284.760000,1.000000,63.262500
max,12908.170000,199.940000,59.990000,149.980000,100.000000,1966.290000,7591.910000,59.000000,3966.260000,1.000000,87.310000

In [175]:
data["riskTier"].unique()

array(['medium', 'low', 'high', 'critical'], dtype=object)

# Data Preprocessing

In [176]:
data=data.drop("riskScore", axis=1)

## Encoding

In [177]:
Tier_order = {'low': 0, 'medium': 1, 'high': 2, 'critical': 3}
Tier_names = ['low', 'medium', 'high', 'critical']

In [178]:
data['riskTier_enc'] = data['riskTier'].map(Tier_order)

In [179]:
data[['riskTier', 'riskTier_enc']].head()

  riskTier  riskTier_enc
0   medium             1
1      low             0
2      low             0
3   medium             1
4      low             0

In [180]:
data['riskTier_enc'].isna().sum()

np.int64(0)

## Define Features and Target

In [181]:
X = data.drop(['riskTier', 'riskTier_enc'], axis=1)
y = data['riskTier_enc']

## Train-Test Split

In [182]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42,stratify=y)

## Feature Scaling

In [183]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Training

In [184]:
# Logistic Regression 

log_model = LogisticRegression(max_iter=500)

log_params = {'C': [0.01, 0.1, 1, 10]}
log_grid = GridSearchCV(log_model, log_params, cv=5)
log_grid.fit(X_train_scaled, y_train)

log_pred = log_grid.predict(X_test_scaled)

print("Logistic Regression")
print("Best Params:", log_grid.best_params_)
print("Accuracy:", accuracy_score(y_test, log_pred))

Logistic Regression
Best Params: {'C': 10}
Accuracy: 0.94

In [185]:
# Random Forest Classifier

rf_model = RandomForestClassifier(random_state=42)

rf_params = {'n_estimators': [100, 200],'max_depth': [None, 5, 10]}
rf_grid = GridSearchCV(rf_model, rf_params, cv=5)
rf_grid.fit(X_train, y_train)

rf_pred = rf_grid.predict(X_test)

print("Random Forest")
print("Best Params:", rf_grid.best_params_)
print("Accuracy:", accuracy_score(y_test, rf_pred))

Random Forest
Best Params: {'max_depth': None, 'n_estimators': 100}
Accuracy: 0.9635

In [186]:
# Gradient Boosting Classifier

gb_model = GradientBoostingClassifier()

gb_params = {'n_estimators': [100, 200],'learning_rate': [0.01, 0.1],'max_depth': [3, 5]}
gb_grid = GridSearchCV(gb_model, gb_params, cv=5)
gb_grid.fit(X_train, y_train)

gb_pred = gb_grid.predict(X_test)

print("Gradient Boosting")
print("Best Params:", gb_grid.best_params_)
print("Accuracy:", accuracy_score(y_test, gb_pred))

Gradient Boosting
Best Params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Accuracy: 0.9675

In [193]:
# SVM

svm_model = SVC(kernel='rbf',random_state=42)

svm_params = {'C': [10],'gamma': ['scale', 0.1, 0.01]}
svm_grid = GridSearchCV(svm_model, svm_params, cv=5)
svm_grid.fit(X_train_scaled, y_train)

svm_pred = svm_grid.predict(X_test_scaled)

print("SVM (RBF)")
print("Best Params:", svm_grid.best_params_)
print("Accuracy:", accuracy_score(y_test, svm_pred))

SVM (RBF)
Best Params: {'C': 10, 'gamma': 'scale'}
Accuracy: 0.949

# Model Comparison

In [194]:
results = pd.DataFrame({"Model": ["Logistic Regression", "Random Forest","Gradient Boosting", "SVM (RBF)"],
"Accuracy": [accuracy_score(y_test, log_pred),
             accuracy_score(y_test, rf_pred),
             accuracy_score(y_test, gb_pred),
             accuracy_score(y_test, svm_pred)]
})

results.sort_values(by="Accuracy", ascending=False)

                 Model  Accuracy
2    Gradient Boosting    0.9675
1        Random Forest    0.9635
3            SVM (RBF)    0.9490
0  Logistic Regression    0.9400

## Model Evaluation

In [195]:
best_pred = gb_pred  # Change based on highest accuracy

print(classification_report(y_test, best_pred))

cm = confusion_matrix(y_test, best_pred)
print(cm)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       956
           1       0.96      0.97      0.97       521
           2       0.93      0.95      0.94       357
           3       0.97      0.85      0.91       166

    accuracy                           0.97      2000
   macro avg       0.96      0.94      0.95      2000
weighted avg       0.97      0.97      0.97      2000

[[947   9   0   0]
 [ 13 507   1   0]
 [  0  13 340   4]
 [  0   0  25 141]]

## Model Saving

In [196]:
import pickle

In [197]:
with open("gradient_boosting_inventory_model.pkl","wb") as f:
    pickle.dump(gb_grid.best_estimator_,f)

In [198]:
with open("tier_mapping.pkl","wb") as f:
    pickle.dump(Tier_order,f)

In [199]:
with open("inventory_scaler.pkl","wb") as f:
    pickle.dump(scaler,f)